[package]
name = "nu-glob2"
version = "0.104.2"
edition = "2021"

[dependencies]
nu-protocol = { path = "../nu-protocol", version = "0.104.2" }
anyhow = "1.0.89"
log = { workspace = true }
rayon = "1.10.0"
